import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Utility to generate an Exit Certificate PDF for a worker
 * In a real app, this might be handled on the backend to prevent tampering,
 * but doing it on the frontend is faster for demo purposes.
 */
export const generateCertificatePDF = async (worker, scoreData) => {
  // Create a temporary hidden DOM element to render the certificate
  const certContainer = document.createElement('div');
  certContainer.style.position = 'absolute';
  certContainer.style.left = '-9999px';
  certContainer.style.top = '-9999px';
  certContainer.style.width = '800px';
  certContainer.style.padding = '40px';
  certContainer.style.backgroundColor = '#ffffff';
  certContainer.style.color = '#1F2937';
  certContainer.style.fontFamily = 'Inter, sans-serif';
  certContainer.style.border = '10px solid #033f63';
  
  // HTML Template for the Certificate
  const date = new Date().toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const overallScore = worker.rating;

  certContainer.innerHTML = `
    <div style="border: 2px solid #E5E7EB; padding: 40px; text-align: center; position: relative;">
      
      <div style="position: absolute; top: 40px; left: 40px; opacity: 0.1;">
        <svg width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="#1E3A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
      </div>

      <h1 style="color: #033f63; font-size: 36px; margin-bottom: 5px; font-weight: 800;">SKILLSETU</h1>
      <p style="color: #28666e; font-weight: 600; letter-spacing: 2px; font-size: 14px; margin-bottom: 40px; text-transform: uppercase;">Skill-Verified Rural Workforce Network</p>
      
      <h2 style="font-size: 28px; margin-bottom: 30px; font-weight: 300;">Professional Exit Certificate</h2>
      
      <p style="font-size: 18px; margin-bottom: 15px;">This is to certify that</p>
      <h3 style="font-size: 32px; font-weight: bold; text-decoration: underline; margin-bottom: 15px; text-transform: capitalize;">${worker.name}</h3>
      <p style="font-size: 16px; color: #4B5563; margin-bottom: 30px;">
        ID: DB-${worker.id.toUpperCase()}<br/>
        Primary Skill: ${worker.skills[0]}
      </p>
      
      <p style="font-size: 16px; margin-bottom: 40px; line-height: 1.6; max-width: 600px; margin-left: auto; margin-right: auto;">
        Has actively participated on the Skillsetu platform and has completed 
        <strong>${worker.reviewsCount}</strong> verified job bookings. Based on feedback from employers, 
        they have maintained an overall performance rating of:
      </p>
      
      <div style="background-color: #F5F7FA; padding: 20px; border-radius: 12px; display: inline-block; margin-bottom: 40px; border: 1px solid #E5E7EB;">
         <div style="font-size: 48px; font-weight: bold; color: #22C55E;">${overallScore} <span style="font-size: 24px; color: #9CA3AF;">/ 5.0</span></div>
         <div style="display: flex; gap: 4px; justify-content: center; margin-top: 10px;">
           ${[1, 2, 3, 4, 5].map(i => `<span style="color: ${i <= Math.round(overallScore) ? '#F59E0B' : '#D1D5DB'}; font-size: 24px;">★</span>`).join('')}
         </div>
      </div>

      <div style="display: flex; justify-content: space-around; margin-top: 50px; text-align: left;">
        <div>
          <p style="font-size: 14px; color: #6B7280; margin-bottom: 5px;">Issue Date</p>
          <p style="font-weight: bold;">${date}</p>
        </div>
        <div>
          <div style="width: 150px; border-bottom: 1px solid #000; margin-bottom: 5px;"></div>
          <p style="font-size: 14px; color: #6B7280;">Authorised Signatory</p>
          <p style="font-size: 12px; color: #9CA3AF;">Platform Admin</p>
        </div>
      </div>
      
      <div style="margin-top: 40px; font-size: 10px; color: #9CA3AF;">
        This certificate is digitally generated by Skillsetu based on aggregated platform data. <br/>
        To verify authenticity, visit skillsetu.in/verify and enter the Worker ID.
      </div>
    </div>
  `;

  document.body.appendChild(certContainer);

  try {
    // Convert DOM to Canvas
    const canvas = await html2canvas(certContainer, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'px',
      format: [canvas.width / 2, canvas.height / 2]
    });

    pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
    
    // Download
    pdf.save(`DakshBharat_Certificate_${worker.name.replace(' ', '_')}.pdf`);
  } catch (err) {
    console.error('Error generating PDF:', err);
    throw err;
  } finally {
    // Cleanup
    document.body.removeChild(certContainer);
  }
};
